function run=runinfo(run, ID)
% This function removes the data and events where data was lost and adds
% info if the run was complete. ! info.duration is derived from the
% textGrid files, so are indicating the duration of the runs as
% indicated by the begin and end beep.
%
% Use as
%   [run]      = runinfo(run, ID)
%
% INPUT:
%       run    = structure of all the runs generated by
%       LoadECGData.m and LoadEvents.m
%       ID         = participant ID (e.g. '110001'); 
%
% OUTPUT
%       run     = run structure whithout the lost data

%% load sub.mat from compareFOG_main to derive run durations
load('sub.mat');

%% remove empty data
switch ID
  case '110001'
  % run 5 and 6 are empty
  run=run([1:4]);
  % run 4 is empty from 260 sec. on
  cfg=[];
  cfg.latency=[run(4).data_ECG.time{1}(1) 260];
  run(4).data_ECG=ft_selectdata(cfg, run(4).data_ECG);
  run(4).events=run(4).events(find([run(4).events.timestamp]<=260));
  run(4).info.complete='no';
  run(4).info.duration=sub(1).rater(1).sessions(4).duration; % ! this is different from the 260 seconds, but is used for the FOG statistics. Please, take this into account when using info.duration for other purposes
  run(4).info.bestlead='II';
  % other runs are complete
  for i=1:3
    run(i).info.complete= 'yes';
    run(i).info.duration=sub(1).rater(1).sessions(i).duration;
    run(i).info.bestlead='II';
  end
  
  case '110002'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(2).rater(1).sessions(i).duration;
      run(i).info.bestlead='LL';
    end
    
  case '110003'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(3).rater(1).sessions(i).duration;
      run(i).info.bestlead='III';
    end
    
  case '110004'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(4).rater(1).sessions(i).duration;      
      run(i).info.bestlead='I';
    end
    
  case '110005' % compared I, II, III
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(5).rater(1).sessions(i).duration;
      if i==6
        run(i).info.bestlead='I';
      else 
        run(i).info.bestlead='II';
      end
    end
    
  case '110006'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(6).rater(1).sessions(i).duration;
      run(i).info.bestlead='LL';
    end
    
  case '110007'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(7).rater(1).sessions(i).duration;
      run(i).info.bestlead='II'; % checked with 'III'
    end
    
  case '110008'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(8).rater(1).sessions(i).duration;
      run(i).info.bestlead='II';
    end
    
  case '110009'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(9).rater(1).sessions(i).duration;
      run(i).info.bestlead='II';
    end
    
  case '110010'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(10).rater(1).sessions(i).duration;
      run(i).info.bestlead='II';
    end
    
  case '110011'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(11).rater(1).sessions(i).duration;
      run(i).info.bestlead='II';
    end
    
  case '110012'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(12).rater(1).sessions(i).duration;
      run(i).info.bestlead='LA';
    end
    
  case '110013'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(13).rater(1).sessions(i).duration;
      run(i).info.bestlead='LA';
    end
    
  case '110014'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(14).rater(1).sessions(i).duration;
      run(i).info.bestlead='I';
    end
    
  case '110015'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(15).rater(1).sessions(i).duration;
      run(i).info.bestlead='I';
    end
    
  case '110016'
    for i=1:length(run)
      run(i).info.complete='yes';
      run(i).info.duration=sub(16).rater(1).sessions(i).duration;
      run(i).info.bestlead='I';
    end
      
end
